dataset_name: 'FashionMNIST'
train_batch_size: 64
learning_rate: 1.0e-3
num_epochs: 10
input_size: [28,28]
input_channels: 1
channels_range: [6, 12, 18, 24, 30, 36, 42]
layers_num: 5
kernel_size: 3
classes: 10
save_model_path_prefix: './models_chkps/fashion_mnist_change_channels'
save_results_path: './results/fashion_mnist_change_channels.json'
save_figs_path: './figures/fashion_mnist_change_channels.pdf'
legend_title: '$C$ (num of channels)'
exp_type: 'change channels'
